[mypy]
python_version = 3.10
mypy_path = src
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
no_implicit_optional = True
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = False

[mypy-tests.*]
ignore_errors = True

[mypy-numpy.*]
follow_imports = skip
follow_imports_for_stubs = True
